// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;

    /// <summary>
    /// Migration metadata for WidenMoneyColumns.
    ///
    /// Target is deliberately null, for the same reason and with the same
    /// consequence as 202610041200000_AddPayments.Designer.cs: the blob cannot be
    /// written by hand, nothing at runtime reads it, and Up() carries the DDL.
    /// </summary>
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WidenMoneyColumns : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202610041400000_WidenMoneyColumns"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}