// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;

    /// <summary>
    /// Migration metadata for AddPayments.
    ///
    /// Target is deliberately null. EF6 normally embeds the target model as a
    /// "Target" resource in a .resx beside this file, and that blob cannot be
    /// written by hand - so rather than ship a fabricated or stale one, there is
    /// none. See the KNOWN GAP note in 202610041200000_AddPayments.cs.
    ///
    /// Nothing at runtime reads it: MigrateDatabaseToLatestVersion applies Up()
    /// to the migrations the database has not recorded, and Up() carries the DDL.
    /// </summary>
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPayments : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "202610041200000_AddPayments"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return null; }
        }
    }
}