<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BE\BE.csproj" />
    <ProjectReference Include="..\BLL\BLL.csproj" />
    <ProjectReference Include="..\DAL\DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stimulsoft.Reports.Engine.NetCore" Version="2022.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\CRMPeyvand\Reports\*.mrt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Reports\%(FileName)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\CRMPeyvand\PersianCulture.cs" Link="PersianCulture.cs" />
  </ItemGroup>
</Project>
